---
  - name: Download
    win_oneget:
      name: "xSmbShare"

  - name: Create profile root
    win_pc_file:
      DestinationPath: "{{ profile_path }}"
      Ensure: Present
      Type: Directory
      Force: True

  - name: Share profile folders
    win_ad_xsmbshare:
      name: profiles
      description: top secret profiles
      FullAccess: "{{ domainnetbios }}\\{{ user_group_str }}"
      path: "{{ profile_path }}"

  - name: Setup perms for profile root
    ps_winacl:
      Path: "{{ profile_path }}"
      User: "{{ item }}"
      Permissions: Write, Read, Synchronize
    with_items:
      - "{{ user_group }}"

  - name: Create user profile
    win_pc_file:
      DestinationPath: "{{ profile_path }}\\{{ item.name }}"
      Ensure: Present
      Type: Directory
      Force: True
      PsDscRunAsCredential_username: "{{ item.name }}"
      PsDscRunAsCredential_password: "{{ item.pass }}"
    with_items: "{{ users }}"

  - name: Add user profile items
    win_pc_file:
      DestinationPath: "{{ profile_path }}\\{{ item[0].name }}\\{{ item[1] }}"
      Ensure: Present
      Type: Directory
      Force: True
      PsDscRunAsCredential_username: "{{ item[0].name }}"
      PsDscRunAsCredential_password: "{{ item[0].pass }}"
    with_nested:
      - "{{ users }}"
      - "{{ folders }}"

  - name: Setup perms for home dir
    ps_winacl:
      Path: "{{ profile_path }}\\{{ item.name }}"
      User: "{{ item.name }}"
      Permissions: FullControl
      InheritFlags: ContainerInherit, ObjectInherit
    with_items:
      - "{{ users }}"



